[site]
title = "Weisheng Xu"
description = "Personal website of Weisheng Xu"
url = "https://wesleyxu224.github.io"

[author]
name = "Weisheng Xu"
title = "research-oriented Red Bird Master (MPhil) Student"
avatar = "/profile.png" # 记得把你的 profile.png 放到 PRISM 的 public/ 文件夹下
bio = "Research-oriented Red Bird Master (MPhil) Student in Robotics and Autonomous Systems at HKUST(GZ). Research focused on Physics-based Humanoid Control and Embodied AI."
location = "Guangzhou, China"
email = "wxu421@connect.hkust-gz.edu.cn"

[social]
github = "wesleyxu224"
scholar = "https://scholar.google.cz/citations?user=iLP3qBEAAAAJ"
orcid = "https://orcid.org/0009-0005-9959-5626"
# 如果有 twitter 等可以继续在这里加： twitter = "你的id"

[navigation]
# 配置顶部的导航栏
items = [
  { label = "Home", path = "/" },
  { label = "Publications", path = "/publications" },
  # { label = "CV", path = "/cv" }, # 如果后续你想加独立简历页，把这行取消注释
]